# Generated by Django 5.1.7 on 2025-03-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_age', models.IntegerField()),
                ('stu_branch', models.CharField(max_length=100)),
                ('stu_image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
