# Generated by Django 5.1.7 on 2025-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recruiter_job_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
